apiVersion: apps/v1
kind: Deployment
metadata:
  name: lotso-documents
  labels:
    app: lotso-documents
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lotso-documents
  template:
    metadata:
      labels:
        app: lotso-documents
    spec:
      initContainers:
        - name: init-gcp-credentials
          image: busybox:1.35.0-uclibc
          command:
            - sh
            - -c
            - "cp /secrets/key.json /tmp/key.json"
          volumeMounts:
            - name: gcp-credentials
              mountPath: /secrets
              readOnly: true
            - name: temp-storage
              mountPath: /tmp
      containers:
        - name: lotso-documents
          image: mpayalal/lotso-documents:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: gcp-credentials
              mountPath: /secrets
              readOnly: true
            - name: temp-storage
              mountPath: /tmp
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /tmp/key.json  # Usar el archivo copiado
          resources:
            limits:
              cpu: "50m"
              memory: "100Mi"
            requests:
              cpu: "50m"
              memory: "100Mi"
      volumes:
        - name: gcp-credentials
          secret:
            secretName: gcp
        - name: temp-storage
          emptyDir: {}
