apiVersion: apps/v1
kind: Deployment
metadata:
  name: lotso-documents
  labels:
    app: lotso-documents
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lotso-documents
  template:
    metadata:
      labels:
        app: lotso-documents
    spec:
      containers:
        - name: lotso-documents
          image: mpayalal/lotso-documents:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
          - name: gcp-sa-volume
            mountPath: /secrets/gcp
            readOnly: true
          env:
          - name: GCP_SA_KEY
            value: /secrets/gcp/key.json
          - name: GCP_BUCKET_NAME
            value: lotso_bucket
          - name: DB_NAME
            value: "marcianos"
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: my-db
                key: DB_USER
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: my-db
                key: DB_PASS
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: my-db
                key: DB_HOST
          resources:
            limits:
              cpu: "50m"
              memory: "100Mi"
            requests:
              cpu: "50m"
              memory: "100Mi"
      volumes:
        - name: gcp-sa-volume
          secret:
            secretName: gcp-sa
